services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    networks:
      - keycloak-network
    command: ["start-dev"]

networks:
  keycloak-network:
    driver: bridge
